# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2018.3.4\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2018.3.4\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\moshe\CLionProjects\project3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\moshe\CLionProjects\project3\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2018.3.4\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2018.3.4\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\moshe\CLionProjects\project3\cmake-build-debug\CMakeFiles C:\Users\moshe\CLionProjects\project3\cmake-build-debug\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\moshe\CLionProjects\project3\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project3

# Build rule for target.
project3: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 project3
.PHONY : project3

# fast build rule for target.
project3/fast:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/build
.PHONY : project3/fast

PhysicalNumber.obj: PhysicalNumber.cpp.obj

.PHONY : PhysicalNumber.obj

# target to build an object file
PhysicalNumber.cpp.obj:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumber.cpp.obj
.PHONY : PhysicalNumber.cpp.obj

PhysicalNumber.i: PhysicalNumber.cpp.i

.PHONY : PhysicalNumber.i

# target to preprocess a source file
PhysicalNumber.cpp.i:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumber.cpp.i
.PHONY : PhysicalNumber.cpp.i

PhysicalNumber.s: PhysicalNumber.cpp.s

.PHONY : PhysicalNumber.s

# target to generate assembly for a file
PhysicalNumber.cpp.s:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumber.cpp.s
.PHONY : PhysicalNumber.cpp.s

PhysicalNumberDemo.obj: PhysicalNumberDemo.cpp.obj

.PHONY : PhysicalNumberDemo.obj

# target to build an object file
PhysicalNumberDemo.cpp.obj:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumberDemo.cpp.obj
.PHONY : PhysicalNumberDemo.cpp.obj

PhysicalNumberDemo.i: PhysicalNumberDemo.cpp.i

.PHONY : PhysicalNumberDemo.i

# target to preprocess a source file
PhysicalNumberDemo.cpp.i:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumberDemo.cpp.i
.PHONY : PhysicalNumberDemo.cpp.i

PhysicalNumberDemo.s: PhysicalNumberDemo.cpp.s

.PHONY : PhysicalNumberDemo.s

# target to generate assembly for a file
PhysicalNumberDemo.cpp.s:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumberDemo.cpp.s
.PHONY : PhysicalNumberDemo.cpp.s

PhysicalNumberTest.obj: PhysicalNumberTest.cpp.obj

.PHONY : PhysicalNumberTest.obj

# target to build an object file
PhysicalNumberTest.cpp.obj:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumberTest.cpp.obj
.PHONY : PhysicalNumberTest.cpp.obj

PhysicalNumberTest.i: PhysicalNumberTest.cpp.i

.PHONY : PhysicalNumberTest.i

# target to preprocess a source file
PhysicalNumberTest.cpp.i:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumberTest.cpp.i
.PHONY : PhysicalNumberTest.cpp.i

PhysicalNumberTest.s: PhysicalNumberTest.cpp.s

.PHONY : PhysicalNumberTest.s

# target to generate assembly for a file
PhysicalNumberTest.cpp.s:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/PhysicalNumberTest.cpp.s
.PHONY : PhysicalNumberTest.cpp.s

Unit.obj: Unit.cpp.obj

.PHONY : Unit.obj

# target to build an object file
Unit.cpp.obj:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/Unit.cpp.obj
.PHONY : Unit.cpp.obj

Unit.i: Unit.cpp.i

.PHONY : Unit.i

# target to preprocess a source file
Unit.cpp.i:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/Unit.cpp.i
.PHONY : Unit.cpp.i

Unit.s: Unit.cpp.s

.PHONY : Unit.s

# target to generate assembly for a file
Unit.cpp.s:
	$(MAKE) -f CMakeFiles\project3.dir\build.make CMakeFiles/project3.dir/Unit.cpp.s
.PHONY : Unit.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... project3
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... PhysicalNumber.obj
	@echo ... PhysicalNumber.i
	@echo ... PhysicalNumber.s
	@echo ... PhysicalNumberDemo.obj
	@echo ... PhysicalNumberDemo.i
	@echo ... PhysicalNumberDemo.s
	@echo ... PhysicalNumberTest.obj
	@echo ... PhysicalNumberTest.i
	@echo ... PhysicalNumberTest.s
	@echo ... Unit.obj
	@echo ... Unit.i
	@echo ... Unit.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

